export const data = [
  {
    id: 0,
    shortdesc: 'Placeholder text for project.',
    longdesc: 'long description',
    img: './images/img.png',
    title: 'Project 1',
    techstack: ['html', 'css', 'javascript'],
    liveurl: 'live url',
    sourceurl: 'source url',
  },
  {
    id: 1,
    shortdesc: 'Placeholder text for project.',
    longdesc: 'long description',
    img: './images/img.png',
    title: 'Project 2',
    techstack: ['html', 'css', 'javascript'], 
    liveurl: 'live url',
    sourceurl: 'source url',
  },
  {
    id: 2,
    shortdesc: 'Placeholder text for project.',
    longdesc: 'long description',
    img: './images/img.png',
    title: 'Project 3',
    techstack: ['html', 'css', 'javascript'],
    liveurl: 'live url',
    sourceurl: 'source url',
  },
]