export const data = [
  {
    id: 0,
    shortdesc: 'shortdescription',
    longdesc: 'long description',
    img: 'image',
    title: 'title',
    techstack: 'html',
    liveurl: 'live url',
    sourceurl: 'source url',
  },
  {
    id: 1,
    shortdesc: 'shortdescription',
    longdesc: 'long description',
    img: 'image',
    title: 'title',
    techstack: 'html',
    liveurl: 'live url',
    sourceurl: 'source url',
  },
  {
    id: 2,
    shortdesc: 'shortdescription',
    longdesc: 'long description',
    img: 'image',
    title: 'title',
    techstack: 'html',
    liveurl: 'live url',
    sourceurl: 'source url',
  },
]